[workspace]
members = [
    "jgnes-proc-macros",
    "jgnes-core",
    "jgnes-renderer",
    "jgnes-native-driver",
    "jgnes-cli",
    "jgnes-gui",
    "jgnes-web",
]
resolver = "2"

[profile.dev]
opt-level = 1

[profile.release-lto]
inherits = "release"
lto = true

[profile.profiling]
inherits = "release"
debug = true

[profile.profiling-lto]
inherits = "profiling"
lto = true
