[workspace]
members = [
    "jgnes-proc-macros",
    "jgnes-core",
    "jgnes-renderer",
    "jgnes-native-driver",
    "jgnes-cli",
    "jgnes-gui",
    "jgnes-web",
]
resolver = "2"

[workspace.dependencies]
# Pin serde to <= 1.0.171 until/unless serde_derive stops including precompiled binaries
serde = { version = "<= 1.0.171", features = ["derive"] }

[profile.dev]
opt-level = 1

[profile.release-lto]
inherits = "release"
lto = true

[profile.profiling]
inherits = "release"
debug = true

[profile.profiling-lto]
inherits = "profiling"
lto = true
