[package]
name = "jgnes-native-driver"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
jgnes-core = { path = "../jgnes-core" }

anyhow = "1.0"
log = "0.4"
sdl2 = "0.35"