#!/usr/bin/env bash

set -euo pipefail

current_rev=$( git rev-parse HEAD )
echo "// Generated by build.sh" > js/current-version.js
echo "export const currentVersion = '$current_rev';" >> js/current-version.js
echo "export default currentVersion;" >> js/current-version.js

toolchain=${NIGHTLY_TOOLCHAIN:-nightly}

RUSTFLAGS="-C target-feature=+atomics,+bulk-memory,+mutable-globals" \
rustup run $toolchain \
wasm-pack build --target web . "$@" -- -Z build-std=panic_abort,std
