name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always
  # Force on Cargo's sparse protocol for crates.io, set to become default behavior in Rust 1.70
  CARGO_REGISTRIES_CRATES_IO_PROTOCOL: sparse

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install latest stable Rust toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable

    - name: Check formatting
      uses: actions-rs/cargo@v1
      with:
        command: fmt
        args: --check

    - name: Install libsdl2
      run: |
        sudo apt-get update && sudo apt-get install -y libsdl2-dev

    - name: Build
      uses: actions-rs/cargo@v1
      with:
        command: build

    - name: Install cranky
      uses: actions-rs/cargo@v1
      with:
        command: install
        args: cargo-cranky

    - name: Check Clippy warnings
      uses: actions-rs/cargo@v1
      with:
        command: cranky
        args: -- -D warnings

    - name: Run tests
      uses: actions-rs/cargo@v1
      with:
        command: test
